name: boring_app
description: Main library of BoringStuff for creating an application
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.1.1

  boringcore:
    git:
      url: https://github.com/BoringStuff-SRL/BoringCore
      ref: main


dev_dependencies:
  flutter_lints: ^2.0.1

flutter: null
