name: boring_app
description: Main library of BoringStuff for creating an application
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.2.0

  boringcore:
    git:
      url: https://github.com/BoringStuff-SRL/BoringCore
      ref: develop-x


dev_dependencies:
  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0-dev.1

flutter: null
