name: boring_app
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.3

  syncfusion_localizations: ^25.2.6

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: null
